class ErrorApi {
  static const Map<int, String> errorsApi = {
    400: 'Requisição inválida',
    401: 'Não autorizado',
    402: 'Pagamento necessário',
    403: 'Proibido',
    404: 'Não encontrado',
    405: 'Não encontrado',
    406: 'Não encontrado',
    407: 'Autenticação de Proxy Necessária',
    408: 'Tempo de solicitação esgotado',
    409: 'Conflito',
    410: 'Perdido',
    411: 'Duração necessária',
    412: 'Solicitação de URL muito Longa',
    413: 'Solicitação da entidade muito extensa',
    414: 'Muito extensa',
    415: 'Tipo de mídia não suportado',
    416: 'Solicitação de faixa não satisfatória',
    417: 'Falha na expectativa',
    500: 'Erro do Servidor Interno',
    501: 'Erro do Servidor Interno',
    502: 'Erro do Servidor Interno',
    503: 'Serviço Indisponível',
    504: 'Tempo limite da Porta de Entrada',
    505: 'Versão HTTP não suportada',
  };
}
